server:
  port: 9001
  # 允许 IP 访问
  address: 0.0.0.0
  servlet:
    context-path: /provider


spring:
  application:
    name: provider-service
  cloud:
    nacos:
      discovery:
        # 集群使用逗号分割
        server-addr: localhost:8848
        cluster-name: shanghai
        metadata:
           version: v2  # 调用指定版本
        namespace: 8610414c-4f96-4653-ba83-3b5bdfbc09cd
        group: DEFAULT_GROUP
      username: nacos
      password: nacos

# actuator
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    health:
      show-details: always