server:
  port: 9100
  # 允许 IP 访问
  address: "0.0.0.0"
  servlet:
    context-path: /consumer


spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        # 集群使用逗号分割
        server-addr: localhost:8848
      username: nacos
      password: nacos

# actuator
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    health:
      show-details: always